SELECT STARNAME
FROM STARSIN, MOVIESTAR
WHERE STARNAME = MOVIESTAR.NAME
AND MOVIESTAR.GENDER = 'M'
AND STARSIN.MOVIETITLE = 'The Usual Suspects';
-------------
SELECT DISTINCT STARNAME
FROM STARSIN, MOVIE
WHERE MOVIEYEAR = 1995 AND STUDIONAME = 'MGM';
-------------
SELECT DISTINCT NAME
FROM MOVIEEXEC, MOVIE
WHERE STUDIONAME = 'MGM' AND PRODUCERC# = CERT#;
-------------
SELECT TITLE 
FROM MOVIE
WHERE MOVIE.LENGTH >
(SELECT LENGTH FROM MOVIE WHERE MOVIE.TITLE = 'Star Wars');
-------------
SELECT NAME 
FROM MOVIEEXEC
WHERE MOVIEEXEC.NETWORTH >
(SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Stephen Spielberg');
-------------
SELECT TITLE
FROM MOVIE, MOVIEEXEC
WHERE MOVIEEXEC.NETWORTH >
(SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Stephen Spielberg')
AND PRODUCERC# = CERT#;

