SELECT DISTINCT COUNTRY 
FROM 
CLASSES
WHERE NUMGUNS = (
SELECT TOP 1 NUMGUNS
FROM CLASSES
ORDER BY NUMGUNS DESC
)

-------------

SELECT DISTINCT CLASS
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME = OUTCOMES.SHIP AND OUTCOMES.RESULT = 'sunk'

-------------

SELECT NAME, SHIPS.CLASS
FROM SHIPS, CLASSES
WHERE SHIPS.CLASS = CLASSES.CLASS AND CLASSES.BORE = 16

-------------

SELECT BATTLES.NAME
FROM BATTLES, OUTCOMES, SHIPS
WHERE BATTLES.NAME = OUTCOMES.BATTLE AND OUTCOMES.SHIP = SHIPS.NAME AND SHIPS.CLASS = 'Kongo'

------------

SELECT DISTINCT SHIPS.CLASS, NAME
FROM SHIPS, CLASSES AS C1
WHERE SHIPS.CLASS = C1.CLASS  AND C1.NUMGUNS >= (SELECT TOP 1 NUMGUNS
FROM CLASSES AS C2 
WHERE C1.BORE = C2.BORE
ORDER BY NUMGUNS DESC)
ORDER BY SHIPS.CLASS

