SELECT DISTINCT MOVIESTAR.name
FROM MOVIESTAR
JOIN MOVIEEXEC
ON MOVIESTAR.NAME = MOVIEEXEC.NAME
WHERE MOVIESTAR.GENDER = 'F'

--------------

SELECT DISTINCT MOVIESTAR.name
FROM MOVIESTAR
JOIN MOVIEEXEC
ON MOVIESTAR.NAME != MOVIEEXEC.NAME

--------------

SELECT TITLE
FROM MOVIE
WHERE MOVIE.LENGTH > (SELECT LENGTH
FROM MOVIE
WHERE MOVIE.TITLE = 'Star Wars')

-------------

SELECT movie.TITLE, movieexec.NAME
FROM MOVIE, MOVIEEXEC
WHERE PRODUCERC# = MOVIEEXEC.CERT# AND MOVIEEXEC.NETWORTH >
(SELECT NETWORTH
FROM MOVIEEXEC
WHERE MOVIEEXEC.NAME = 'Merv Griffin')

------------
