SELECT NAME, TITLE
FROM MOVIE, MOVIEEXEC
WHERE MOVIE.PRODUCERC# = MOVIEEXEC.CERT# AND MOVIEEXEC.NAME = (
SELECT NAME FROM 
MOVIEEXEC, MOVIE
WHERE MOVIE.PRODUCERC# = MOVIEEXEC.CERT# AND MOVIE.TITLE = 'Star Wars'
)

----------------

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC, MOVIE, STARSIN
WHERE MOVIEEXEC.CERT# = MOVIE.PRODUCERC# AND MOVIE.TITLE = STARSIN.MOVIETITLE AND STARSIN.STARNAME = 'Harrison Ford'

----------------

SELECT NAME, STARNAME
FROM STUDIO,STARSIN,MOVIE
WHERE STUDIO.NAME = MOVIE.STUDIONAME AND MOVIE.TITLE = STARSIN.MOVIETITLE
ORDER BY STUDIO.NAME

----------------
SELECT DISTINCT STARNAME
FROM STARSIN, MOVIE, MOVIEEXEC
WHERE STARSIN.MOVIETITLE = MOVIE.TITLE AND MOVIE.PRODUCERC# = MOVIEEXEC.CERT# AND MOVIEEXEC.NETWORTH = (
SELECT TOP 1 NETWORTH
FROM MOVIEEXEC
ORDER BY NETWORTH DESC
)

---------------
SELECT DISTINCT NAME AS N
FROM MOVIESTAR, STARSIN
WHERE (SELECT COUNT(*) FROM STARSIN WHERE  STARSIN.STARNAME = MOVIESTAR.NAME) = 0

---------------
